/*
Config file handler generated by Nach's Config file handler creator.
*/

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "cfg.h"

#define LINE_LENGTH 262144
static char line[LINE_LENGTH];

static char *encode_string(const char *str) {
	size_t i = 0;
	line[i++] = '\"';
	while (*str) {
		if ((*str == '\\') ||
			(*str == '\"') ||
			(*str == '\'') ||
			(*str == '\n') ||
			(*str == '\t')) {
			line[i++] = '\\';
		}
		line[i++] = *str++;
	}
	line[i++] = '\"';
	line[i] = 0;
	return (line);
}

static char *decode_string(char *str) {
	size_t str_len = strlen(str), i = 0;
	char *dest = str;

	if ((str_len > 1) && (*str == '\"') && (str[str_len - 1] == '\"')) {
		memmove(str, str + 1, str_len - 2);
		str[str_len - 2] = 0;

		while (*str) {
			if (*str == '\\') {
				str++;
			}
			dest[i++] = *str++;
		}
	}
	dest[i] = 0;
	return (dest);
}

static char *find_next_match(char *str, char match_char) {
	char *pos = 0;

	while (*str) {
		if (*str == match_char) {
			pos = str;
			break;
		}
		if (*str == '\\') {
			if (str[1]) {
				str++;
			} else {
				break;
			}
		}
		str++;
	}
	return (pos);
}

static char *find_str(char *str, char *match_str) {
	char *pos = 0;

	while (*str) {
		if (strchr(match_str, *str)) {
			pos = str;
			break;
		}
		if ((*str == '\"') || (*str == '\'')) {
			char *match_pos = 0;
			if ((match_pos = find_next_match(str + 1, *str))) {
				str = match_pos;
			}
		}
		str++;
	}
	return (pos);
}

static int atoui(const char *nptr) {
	return (strtoul(nptr, 0, 10));
}

// Copyright (C) 1997-2008 ZSNES Team ( zsKnight, _Demo_, pagefault, Nach )
//
// http://www.zsnes.com
// http://sourceforge.net/projects/zsnes
// https://zsnes.bountysource.com
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// version 2 as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

unsigned char GUIComboGameSpec = 0;

unsigned char GameSpecificInput = 0;

unsigned char Show224Lines = 1;

unsigned char newengen = 1;

unsigned char bgfixer = 0;

unsigned char AutoPatch = 1;

unsigned char DisplayInfo = 1;

unsigned char RomInfo = 1;

unsigned char FPSAtStart = 0;

unsigned char TimerEnable = 0;

unsigned char TwelveHourClock = 0;

unsigned char ClockBox = 1;

unsigned char SmallMsgText = 0;

unsigned char GUIEnableTransp = 0;

unsigned char ScreenShotFormat = 0;

unsigned char cvidmode = 0;

unsigned int CustomResX = 640;
unsigned int CustomResY = 480;

unsigned char vsyncon = 0;

char libAoDriver[10];

unsigned char SPCDisable = 0;

unsigned char soundon = 1;

unsigned char StereoSound = 1;

unsigned char RevStereo = 0;

unsigned char Surround = 0;

unsigned int SoundQuality = 5;

unsigned char MusicRelVol = 100;

unsigned char SoundInterpType = 1;

unsigned char LowPassFilterType = 0;

unsigned char EchoDis = 0;

unsigned char RewindStates = 8;
unsigned char RewindFrames = 15;

unsigned char nosaveSRAM = 0;

unsigned char SRAMSave5Sec = 0;

unsigned char SRAMState = 1;

unsigned char LatestSave = 0;

unsigned char AutoIncSaveSlot = 0;

unsigned char AutoIncSaveSlotBlock = 0;

unsigned char AutoState = 0;

unsigned char PauseLoad = 0;
unsigned char PauseRewind = 0;

unsigned int per2exec = 100;

unsigned char HacksDisable = 0;

unsigned char frameskip = 0;

unsigned char maxskip = 9;

unsigned char FastFwdToggle = 0;
unsigned char FFRatio = 8;
unsigned char SDRatio = 0;

unsigned char EmuSpeed = 29;

unsigned char SPC7110Cache = 1;

char ROMPath[1024];
char SRAMPath[1024];
char SStatePath[1024];
char SnapPath[1024];
char IPSPath[1024];
char MoviePath[1024];
char SPCPath[1024];
char CHTPath[1024];
char ComboPath[1024];
char INPPath[1024];
char BSXPath[1024];
char STPath[1024];
char GNextPath[1024];
char SGPath[1024];

unsigned char RelPathBase = 0;

unsigned char guioff = 0;

unsigned char showallext = 0;

unsigned char GUIloadfntype = 0;

unsigned char prevloadiname[280];
unsigned char prevloaddnamel[5120];
unsigned char prevloadfnamel[5120];

unsigned char prevlfreeze = 0;

unsigned char GUIRClick = 0;

unsigned char lhguimouse = 0;

unsigned char mouseshad = 1;

unsigned char esctomenu = 1;

unsigned char JoyPad1Move = 0;

unsigned char newfont = 0;

unsigned char savewinpos = 0;

int GUIwinposx[] = {0, 6, 65, 33, 42, 2, 34, 6, 64, 8, 8, 33, 56, 64, 56, 5, 3, 28, 48, 6, 28, 53, 0};
int GUIwinposy[] = {0, 20, 70, 30, 20, 20, 20, 20, 30, 30, 20, 20, 60, 30, 60, 20, 20, 60, 60, 20, 30, 20, 0};

unsigned char GUIEffect = 1;

unsigned char GUIRAdd = 15;
unsigned char GUIGAdd = 10;
unsigned char GUIBAdd = 31;
unsigned char GUITRAdd = 0;
unsigned char GUITGAdd = 10;
unsigned char GUITBAdd = 31;
unsigned char GUIWRAdd = 8;
unsigned char GUIWGAdd = 8;
unsigned char GUIWBAdd = 25;

unsigned char AutoLoadCht = 0;

unsigned char CheatSrcByteSize = 0;

unsigned char CheatSrcByteBase = 0;

unsigned char CheatSrcSearchType = 0;

unsigned char CheatUpperByteOnly = 0;

unsigned char MovieDisplayFrame = 0;

unsigned char MovieStartMethod = 0;

unsigned char MZTForceRTR = 0;

unsigned char MovieVideoMode = 4;

unsigned char MovieAudio = 1;

unsigned char MovieAudioCompress = 1;

unsigned char MovieVideoAudio = 1;

unsigned int KeyExtraEnab1 = 0;
unsigned int KeyExtraEnab2 = 0;
unsigned int KeyExtraRotate = 8;

unsigned int KeySaveState = 60;
unsigned int KeyStateSelct = 61;
unsigned int KeyLoadState = 62;
unsigned int KeyIncStateSlot = 0;
unsigned int KeyDecStateSlot = 0;
unsigned int KeyStateSlc0 = 0;
unsigned int KeyStateSlc1 = 0;
unsigned int KeyStateSlc2 = 0;
unsigned int KeyStateSlc3 = 0;
unsigned int KeyStateSlc4 = 0;
unsigned int KeyStateSlc5 = 0;
unsigned int KeyStateSlc6 = 0;
unsigned int KeyStateSlc7 = 0;
unsigned int KeyStateSlc8 = 0;
unsigned int KeyStateSlc9 = 0;
unsigned int KeyRewind = 0;

unsigned int KeyFastFrwrd = 41;
unsigned int KeySlowDown = 0;
unsigned int KeyFRateUp = 0;
unsigned int KeyFRateDown = 0;
unsigned int KeyEmuSpeedUp = 0;
unsigned int KeyEmuSpeedDown = 0;
unsigned int KeyResetSpeed = 0;

unsigned int EMUPauseKey = 25;
unsigned int INCRFrameKey = 0;

unsigned int KeyBGDisble0 = 2;
unsigned int KeyBGDisble1 = 3;
unsigned int KeyBGDisble2 = 4;
unsigned int KeyBGDisble3 = 5;
unsigned int KeySprDisble = 6;

unsigned int KeyDisableSC0 = 63;
unsigned int KeyDisableSC1 = 64;
unsigned int KeyDisableSC2 = 65;
unsigned int KeyDisableSC3 = 66;
unsigned int KeyDisableSC4 = 67;
unsigned int KeyDisableSC5 = 68;
unsigned int KeyDisableSC6 = 87;
unsigned int KeyDisableSC7 = 88;

unsigned int KeyVolUp = 0;
unsigned int KeyVolDown = 0;

unsigned int KeyQuickExit = 0;
unsigned int KeyQuickLoad = 0;
unsigned int KeyQuickRst = 0;
unsigned int KeyResetAll = 7;

unsigned int KeyQuickClock = 0;

unsigned int KeyQuickChat = 20;

unsigned int KeyQuickSnapShot = 0;

unsigned int KeyQuickSaveSPC = 0;

unsigned int KeyUsePlayer1234 = 0;

unsigned int KeyDisplayFPS = 0;

unsigned int KeyNewGfxSwt = 9;
unsigned int KeyWinDisble = 10;
unsigned int KeyOffsetMSw = 11;

unsigned int KeyInsrtChap = 0;
unsigned int KeyPrevChap = 0;
unsigned int KeyNextChap = 0;

unsigned int KeyRTRCycle = 0;

unsigned char TimeChecker = 0;
unsigned int PrevBuildNum = 0;

unsigned char FirstTimeData = 0;

unsigned char cfgdontsave = 0;

static unsigned char psr_init_done = 0;
static void init_cfg_vars() {
	if (!psr_init_done) {
		psr_init_done = 1;

		strcpy(libAoDriver, "auto");
		strcpy(ROMPath, "");
		strcpy(SRAMPath, "");
		strcpy(SStatePath, "");
		strcpy(SnapPath, "");
		strcpy(IPSPath, "");
		strcpy(MoviePath, "");
		strcpy(SPCPath, "");
		strcpy(CHTPath, "");
		strcpy(ComboPath, "");
		strcpy(INPPath, "");
		strcpy(BSXPath, "");
		strcpy(STPath, "");
		strcpy(GNextPath, "");
		strcpy(SGPath, "");
		memset(prevloadiname, 0, 280);
		memset(prevloaddnamel, 0, 5120);
		memset(prevloadfnamel, 0, 5120);
	}
}

static char *base94_encode(size_t size) {
	unsigned int i;
	static char buffer[] = {0, 0, 0, 0, 0, 0};
	for (i = 0; i < 5; i++) {
		buffer[i] = ' ' + (char)(size % 94);
		size /= 94;
	}
	return (buffer);
}

static char *char_array_pack(const char *str, size_t len) {
	char packed[LINE_LENGTH];
	char *p = packed;
	while (len) {
		if (*str) {
			size_t length = strlen(str);
			strcpy(p, encode_string(str));
			str += length;
			len -= length;
			p += strlen(p);
		} else {
			size_t i = 0;
			while (len && !*str) {
				i++;
				str++;
				len--;
			}

			sprintf(p, "0%s", encode_string(base94_encode(i)));
			p += strlen(p);
		}
		*p++ = '\\';
	}
	p[-1] = 0;
	strcpy(line, packed);
	return (line);
}

static void write_int_array(int (*outf)(void *, const char *, ...), void *fp, const char *var_name, int *var, size_t size, const char *comment) {
	size_t i;
	outf(fp, "%s=%d", var_name, (int)*var);
	for (i = 1; i < size; i++) {
		outf(fp, ",%d", (int)(var[i]));
	}
	if (comment) {
		outf(fp, " ;%s", comment);
	}
	outf(fp, "\n");
}

static void write_cfg_vars_internal(void *fp, int (*outf)(void *, const char *, ...)) {
	outf(fp, ";%s\n", " PSR-produced config file (stock default in CAPS)");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Note, if you\'re worried you messed up a setting, removing the line will have");
	outf(fp, ";%s\n", " ZSNES use the default settings for that option.");
	outf(fp, ";%s\n", " The next time ZSNES is run, the line will reappear with the default settings.");
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Input --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " For other input settings see zinput.cfg");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable Game-Specific Key Combos (0 = NO, 1 = Yes)");
	outf(fp, "GUIComboGameSpec=%u\n", GUIComboGameSpec);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable Game-Specific Key Input (0 = NO, 1 = Yes)");
	outf(fp, "GameSpecificInput=%u\n", GameSpecificInput);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Options --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Show 224 Lines (0 = No, 1 = YES)");
	outf(fp, ";%s\n", " Toggle off if you do not want to see the last line");
	outf(fp, "Show224Lines=%u\n", Show224Lines);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable New Graphics Engine (0 = No, 1 = YES)");
	outf(fp, ";%s\n", " Toggle off when there are graphical problems in the new graphics engine");
	outf(fp, "newengen=%u\n", newengen);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable Older Graphics Engine Tweak (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Enable this to see if it helps with rendering problems");
	outf(fp, ";%s\n", " Only works with old graphic engine");
	outf(fp, "bgfixer=%u\n", bgfixer);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Auto-Patch ROM with IPS (0 = No, 1 = YES)");
	outf(fp, "AutoPatch=%u\n", AutoPatch);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Display ROM Info on Load (0 = No, 1 = YES)");
	outf(fp, "DisplayInfo=%u\n", DisplayInfo);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Log Info About the Last ROM Loaded to rominfo.txt (0 = No, 1 = YES)");
	outf(fp, "RomInfo=%u\n", RomInfo);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable FPS Counter when ZSNES is Started (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " This option is disabled when manual frameskip is in use.");
	outf(fp, "FPSAtStart=%u\n", FPSAtStart);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Display Clock (0 = NO, 1 = Yes)");
	outf(fp, "TimerEnable=%u\n", TimerEnable);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Change Clock Mode (0 = 24 HOUR, 1 = 12 Hour)");
	outf(fp, "TwelveHourClock=%u\n", TwelveHourClock);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Display Black Box Around Clock (0 = No, 1 = YES)");
	outf(fp, "ClockBox=%u\n", ClockBox);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Use Small Font for Messages (0 = NO, 1 = Yes)");
	outf(fp, "SmallMsgText=%u\n", SmallMsgText);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Transparent Messages - doesn\'t work with small font (0 = NO, 1 = Yes)");
	outf(fp, "GUIEnableTransp=%u\n", GUIEnableTransp);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Snapshot Format (0 = BMP)");
	outf(fp, "ScreenShotFormat=%u\n", ScreenShotFormat);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Video --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " Video Mode [0..22]");
	outf(fp, ";%s\n", "  0 = VARIABLE   ODR WIN");
	outf(fp, ";%s\n", "  1 = VARIABLE   ODS WIN");
	outf(fp, ";%s\n", "  2 = CUSTOM     ODR FULL");
	outf(fp, ";%s\n", "  3 = CUSTOM     ODS FULL");
	outf(fp, ";%s\n", " You need to select the custom video mode and modify CustomResX/Y to properly");
	outf(fp, ";%s\n", " use custom res support.");
	outf(fp, "cvidmode=%u\n", cvidmode);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Custom Resolution X and Y for Custom Video Modes [256x224..2048x1536]");
	outf(fp, "CustomResX=%u\n", CustomResX);
	outf(fp, "CustomResY=%u\n", CustomResY);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Sync Frames to Monitor Refresh Rate (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " It is not recommended to be used if you cannot normally sustain 60fps");
	outf(fp, ";%s\n", " OpenGL only - You need SDL 1.2.10 or later to use this.");
	outf(fp, ";%s\n", " VSync is automatically enforced in SDL software modes.");
	outf(fp, "vsyncon=%u\n", vsyncon);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Sound --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " libAO driver to use. Use zsnes --help to see valid list.");
	outf(fp, ";%s\n", " However \"auto\" (to automatically pick best one), and \"sdl\" should");
	outf(fp, ";%s\n", " always be available.");
	outf(fp, "libAoDriver=%s\n", encode_string(libAoDriver));
	outf(fp, "\n");
	outf(fp, ";%s\n", " Disable SPC Emulation (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Disabling SPC emulation can improve performance, but at the expense of");
	outf(fp, ";%s\n", " emulation accuracy. There will be no sound output and games might crash.");
	outf(fp, "SPCDisable=%u\n", SPCDisable);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable Sound Emulation (0 = Off, 1 = ON) - disable if you need the performance");
	outf(fp, ";%s\n", " If SPC emulation is disabled, there will be no sound output.");
	outf(fp, "soundon=%u\n", soundon);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable Stereo Sound (0 = Off, 1 = ON) - disable if you need the performance");
	outf(fp, "StereoSound=%u\n", StereoSound);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Swap Left Audio Channel w/Right (0 = NO, 1 = Yes)");
	outf(fp, "RevStereo=%u\n", RevStereo);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Simulate Surround Sound (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Enable a simulated 2 speaker surround sound effect.");
	outf(fp, ";%s\n", " Do not enable if playing a game that has its own surround sound effects.");
	outf(fp, ";%s\n", " Stereo Sound must be enabled for this to work.");
	outf(fp, "Surround=%u\n", Surround);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Sampling Rate: (0 = 8000Hz, 1 = 11025Hz, 2 = 22050Hz, 3 = 44100Hz,");
	outf(fp, ";%s\n", "                             4 = 16000Hz, 5 = 32000Hz, 6 = 48000Hz)");
	outf(fp, ";%s\n", " Using any other sound frequencies other than the default 32000Hz");
	outf(fp, ";%s\n", " is COMPLETELY UNACCEPTABLE in use for sound bug reports.");
	outf(fp, "SoundQuality=%u\n", SoundQuality);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Sound Volume Level [0..100]");
	outf(fp, "MusicRelVol=%u\n", MusicRelVol);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable Sound Interpolation (0 = None, 1 = GAUSSIAN, 2 = Cubic, 3 = 8-point)");
	outf(fp, ";%s\n", " Sound interpolation smooths out the waveform of lower frequency sounds.");
	outf(fp, ";%s\n", " Using any other setting other than the default Gaussian interpolation is");
	outf(fp, ";%s\n", " COMPLETELY UNACCEPTABLE in sound bug reports.");
	outf(fp, "SoundInterpType=%u\n", SoundInterpType);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Enable Low-Pass Filter (0 = NONE, 1 = Simple, 2 = Dynamic, 3 = Hi-quality)");
	outf(fp, ";%s\n", " A low-pass filter improves the bass in the sounds.");
	outf(fp, ";%s\n", " This is useful if you have a Subwoofer.");
	outf(fp, "LowPassFilterType=%u\n", LowPassFilterType);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Disable Echo (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Disables the echo effect in the sound.");
	outf(fp, "EchoDis=%u\n", EchoDis);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Saves --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Number of Rewind States [0..99]");
	outf(fp, "RewindStates=%u\n", RewindStates);
	outf(fp, ";%s\n", " Delay between rewinds [1..99] - (1 = 200ms, 5 = 1s, 10 = 2s)");
	outf(fp, "RewindFrames=%u\n", RewindFrames);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Don\'t Save SRAM (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Only enable this if you don\'t want to Save SRAM at any given time.");
	outf(fp, ";%s\n", " This option will make Update SRAM in Real-Time useless.");
	outf(fp, "nosaveSRAM=%u\n", nosaveSRAM);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Update SRAM in Real-Time (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " This is useful if you fear something will prevent ZSNES from exiting normally.");
	outf(fp, ";%s\n", " It is required to play games that store important values directly to SRAM.");
	outf(fp, ";%s\n", " ZSNES normally updates SRAM on exit.");
	outf(fp, ";%s\n", " If Don\'t Save SRAM is enabled, this option is useless.");
	outf(fp, "SRAMSave5Sec=%u\n", SRAMSave5Sec);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Load SRAM w/Savestates (0 = No, 1 = YES)");
	outf(fp, ";%s\n", " Enable this when you want to use the SRM that is stored within the savestate.");
	outf(fp, ";%s\n", " Warning: You will overwrite the existing SRM that you are currently using.");
	outf(fp, ";%s\n", " It is required to properly use states with games storing important values");
	outf(fp, ";%s\n", " directly in SRM.");
	outf(fp, "SRAMState=%u\n", SRAMState);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Select Latest Save State Slot on Game Load (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Enable this if you want to load the last saved savestate quickly");
	outf(fp, ";%s\n", " (via the load savestate button/GUI option) after loading the game.");
	outf(fp, "LatestSave=%u\n", LatestSave);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Auto Increment State Slot First, then Save State (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Enable this if you have a tendency in saving accidentally to an existing");
	outf(fp, ";%s\n", " savestate.");
	outf(fp, "AutoIncSaveSlot=%u\n", AutoIncSaveSlot);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Save in 10 save block (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " This may be handy if you want to save within a block (0-9, 10-19, etc.)");
	outf(fp, "AutoIncSaveSlotBlock=%u\n", AutoIncSaveSlotBlock);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Auto State Save/Load (0 = NO, 1 = Yes) - uses a special state");
	outf(fp, ";%s\n", " Enable this if you wish a special state to be saved on a visit to the GUI.");
	outf(fp, ";%s\n", " This state will automatically be loaded when you load a game.");
	outf(fp, "AutoState=%u\n", AutoState);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Pause Emulation After Loading a Save State (0 = NO, 1 = Yes)");
	outf(fp, "PauseLoad=%u\n", PauseLoad);
	outf(fp, ";%s\n", " Pause Emulation After Using Rewind (0 = NO, 1 = Yes)");
	outf(fp, "PauseRewind=%u\n", PauseRewind);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Emulation --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Percent to Execute [50..150] - only modify if you know what you are doing");
	outf(fp, ";%s\n", " Changing this value may help certain games run.");
	outf(fp, "per2exec=%u\n", per2exec);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Disable Hacks (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Set this to 1 if you want to disable game specific hacks");
	outf(fp, "HacksDisable=%u\n", HacksDisable);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Frameskip: [0..10] (0 = AUTO, 1-10 = Manual 0-9)");
	outf(fp, "frameskip=%u\n", frameskip);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Max Frameskip Allowed for Auto Frameskip [0..9]");
	outf(fp, "maxskip=%u\n", maxskip);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Fastforward/Slowdown Keys Behaviour (0 = HELD, 1 = Toggle)");
	outf(fp, "FastFwdToggle=%u\n", FastFwdToggle);
	outf(fp, ";%s\n", " Fastforward/Slowdown Factors [0..28] (0 = factor 2, 28 = factor 30)");
	outf(fp, "FFRatio=%u\n", FFRatio);
	outf(fp, "SDRatio=%u\n", SDRatio);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Emulation Speed Throttle [0..58] (0 = speed/30, 29 = 1x, 58 = 30x)");
	outf(fp, ";%s\n", " Fast-forward multiplicator is currently inaccurate");
	outf(fp, "EmuSpeed=%u\n", EmuSpeed);
	outf(fp, "\n");
	outf(fp, ";%s\n", " SPC7110 Cache (0 = No, 1 = YES)");
	outf(fp, ";%s\n", " Good for slower PCs. However not good if less than 32MB of RAM free.");
	outf(fp, "SPC7110Cache=%u\n", SPC7110Cache);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Paths --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " It is suggested to go to GUI->Paths and modify the paths from there.");
	outf(fp, ";%s\n", " ROMs directory");
	outf(fp, "ROMPath=%s\n", encode_string(ROMPath));
	outf(fp, ";%s\n", " Save states & SRAMs, snapshots, SPCs");
	outf(fp, "SRAMPath=%s\n", encode_string(SRAMPath));
	outf(fp, "SStatePath=%s\n", encode_string(SStatePath));
	outf(fp, "SnapPath=%s\n", encode_string(SnapPath));
	outf(fp, "IPSPath=%s\n", encode_string(IPSPath));
	outf(fp, "MoviePath=%s\n", encode_string(MoviePath));
	outf(fp, "SPCPath=%s\n", encode_string(SPCPath));
	outf(fp, "CHTPath=%s\n", encode_string(CHTPath));
	outf(fp, "ComboPath=%s\n", encode_string(ComboPath));
	outf(fp, "INPPath=%s\n", encode_string(INPPath));
	outf(fp, ";%s\n", " BIOS/base carts (BS-X, Sufami Turbo, Same Game & SD Gundam G-Next)");
	outf(fp, "BSXPath=%s\n", encode_string(BSXPath));
	outf(fp, "STPath=%s\n", encode_string(STPath));
	outf(fp, "GNextPath=%s\n", encode_string(GNextPath));
	outf(fp, "SGPath=%s\n", encode_string(SGPath));
	outf(fp, "\n");
	outf(fp, ";%s\n", " Relative Path Base (0 = Config dir, 1 = ROM Dir)");
	outf(fp, ";%s\n", " Change the default base path used by ZSNES when using relative paths");
	outf(fp, "RelPathBase=%u\n", RelPathBase);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- GUI --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Disable GUI (0 = NO, 1 = Yes)");
	outf(fp, "guioff=%u\n", guioff);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Show All Files in \'Load Game\' Menu (0 = NO, 1 = Yes)");
	outf(fp, "showallext=%u\n", showallext);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Filename Display Mode (0 = LONG FILENAME, 1 = Internal header name)");
	outf(fp, "GUIloadfntype=%u\n", GUIloadfntype);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Recent games played, you shouldn\'t edit this manually (8.3 / Paths / LFN)");
	outf(fp, "prevloadiname=%s\n", char_array_pack((char *)prevloadiname, 280));
	outf(fp, "prevloaddnamel=%s\n", char_array_pack((char *)prevloaddnamel, 5120));
	outf(fp, "prevloadfnamel=%s\n", char_array_pack((char *)prevloadfnamel, 5120));
	outf(fp, "\n");
	outf(fp, ";%s\n", " Freeze Recent Games List (0 = NO, 1 = Yes)");
	outf(fp, "prevlfreeze=%u\n", prevlfreeze);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Right Mouse Click Enters/Exits GUI (0 = NO, 1 = Yes)");
	outf(fp, "GUIRClick=%u\n", GUIRClick);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Left Handed Mouse Behavior for GUI (0 = NO SWAP, 1 = Swap)");
	outf(fp, ";%s\n", " (swap left and right buttons)");
	outf(fp, "lhguimouse=%u\n", lhguimouse);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Show Mouse Cursor Shadow (0 = No, 1 = YES)");
	outf(fp, ";%s\n", " Displays a shadow under the mouse cursor.");
	outf(fp, "mouseshad=%u\n", mouseshad);
	outf(fp, "\n");
	outf(fp, ";%s\n", " ESC to Game Menu (0 = No, 1 = YES)");
	outf(fp, ";%s\n", " If yes, visiting the GUI will have the Game Menu automatically selected.");
	outf(fp, ";%s\n", " It will also enable the main menu keyboard shortcuts.");
	outf(fp, "esctomenu=%u\n", esctomenu);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Control the GUI Using Gamepad 1 (0 = NO, 1 = Yes)");
	outf(fp, "JoyPad1Move=%u\n", JoyPad1Move);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Use Custom Font (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " The font currently reads off a format as defined by zfile.txt");
	outf(fp, "newfont=%u\n", newfont);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Save GUI Window Positions (0 = NO, 1 = Yes)");
	outf(fp, "savewinpos=%u\n", savewinpos);
	outf(fp, "\n");
	outf(fp, ";%s\n", " GUI windows X/Y coordinates - GUI setup showing windows #");
	outf(fp, "\n");
	outf(fp, ";%s\n", "    Game          Config        Cheat      Netplay       Misc");
	outf(fp, ";%s\n", " -------------------------------------------------------------------");
	outf(fp, ";%s\n", "  1:Load         3:Input      7:Add Code  [Internet]   9:Misc Keys");
	outf(fp, ";%s\n", "    Run          -------      7:Browse                10:GUI Opts");
	outf(fp, ";%s\n", " 12:Reset       17:Devices   13:Search                15:Movie Opt");
	outf(fp, ";%s\n", "  -------       18:Chip Cfg                           16:Key Comb.");
	outf(fp, ";%s\n", " 14:Save State   -------                                 Save Cfg");
	outf(fp, ";%s\n", "  2:Open State   4:Options                             -------");
	outf(fp, ";%s\n", " 14:Pick State   5:Video                              11:About");
	outf(fp, ";%s\n", "  -------        6:Sound");
	outf(fp, ";%s\n", "    Quit        19:Paths");
	outf(fp, ";%s\n", "                20:Saves");
	outf(fp, ";%s\n", "                21:Speed");
	outf(fp, "\n");
	outf(fp, ";%s\n", " X positions [-233..254] (windows #0 to #22)");
	write_int_array(outf, fp, "GUIwinposx", GUIwinposx, 23, 0);
	outf(fp, ";%s\n", " Y positions [8..221] (windows #0 to #22)");
	write_int_array(outf, fp, "GUIwinposy", GUIwinposy, 23, 0);
	outf(fp, "\n");
	outf(fp, ";%s\n", " GUI Background Effect");
	outf(fp, ";%s\n", " (0 = NONE, 1 = Snow, 2 = Water A, 3 = Water B, 4 = Burn, 5 = Smoke)");
	outf(fp, "GUIEffect=%u\n", GUIEffect);
	outf(fp, "\n");
	outf(fp, ";%s\n", " GUI Palette Mods:");
	outf(fp, ";%s\n", " Background RGB Tint [0..31]");
	outf(fp, "GUIRAdd=%u\n", GUIRAdd);
	outf(fp, "GUIGAdd=%u\n", GUIGAdd);
	outf(fp, "GUIBAdd=%u\n", GUIBAdd);
	outf(fp, ";%s\n", " Titlebar RGB Tint [0..31]");
	outf(fp, "GUITRAdd=%u\n", GUITRAdd);
	outf(fp, "GUITGAdd=%u\n", GUITGAdd);
	outf(fp, "GUITBAdd=%u\n", GUITBAdd);
	outf(fp, ";%s\n", " Windows RGB Tint [0..31]");
	outf(fp, "GUIWRAdd=%u\n", GUIWRAdd);
	outf(fp, "GUIWGAdd=%u\n", GUIWGAdd);
	outf(fp, "GUIWBAdd=%u\n", GUIWBAdd);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Cheats --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Autoload .CHT files (0 = NO, 1 = Yes)");
	outf(fp, ";%s\n", " Enable the use of stored cheat files on load.");
	outf(fp, "AutoLoadCht=%u\n", AutoLoadCht);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Selected Size Search (0 = 1 BYTE, 1 = 2B, 2 = 3B, 3 = 4B)");
	outf(fp, "CheatSrcByteSize=%u\n", CheatSrcByteSize);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Selected Numerical Base (0 = DECIMAL, 1 = Hexadecimal)");
	outf(fp, "CheatSrcByteBase=%u\n", CheatSrcByteBase);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Search Type (0 = EXACT VALUE, 1 = Comparative)");
	outf(fp, "CheatSrcSearchType=%u\n", CheatSrcSearchType);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Add Code for Most Significant Byte Only (0 = NO, 1 = Yes)");
	outf(fp, "CheatUpperByteOnly=%u\n", CheatUpperByteOnly);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Movies --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " For other input settings see zmovie.cfg");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Display Movie Frame # During Record/Replay (0 = NO, 1 = Yes)");
	outf(fp, "MovieDisplayFrame=%u\n", MovieDisplayFrame);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Movie Default Start Method (0 = NOW,   1 = Power-On,");
	outf(fp, ";%s\n", "                             2 = Reset, 3 = Power-On without SRAM)");
	outf(fp, "MovieStartMethod=%u\n", MovieStartMethod);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Switch Modes when Loading a Movie State (0 = NO, 1 = Switch to Record, 2 = Switch to Playback)");
	outf(fp, "MZTForceRTR=%u\n", MZTForceRTR);
	outf(fp, "\n");
	outf(fp, ";%s\n", " ZMV -> AVI Conversion Mode: (0 = No Video, 1 = Raw Video, 2 = Ffv1,");
	outf(fp, ";%s\n", "                              3 = x264,     4 = XVID,      5 = Custom)");
	outf(fp, ";%s\n", " The compression codecs can only be used if you provide them yourself.");
	outf(fp, ";%s\n", " See zmovie.cfg for details.");
	outf(fp, "MovieVideoMode=%u\n", MovieVideoMode);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Dump Audio Along w/Video (0 = No, 1 = YES)");
	outf(fp, "MovieAudio=%u\n", MovieAudio);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Compress Audio Stream On-The-Fly (0 = No, 1 = YES)");
	outf(fp, ";%s\n", " The compression codecs can only be used if you provide them yourself.");
	outf(fp, ";%s\n", " See zmovie.cfg for details.");
	outf(fp, "MovieAudioCompress=%u\n", MovieAudioCompress);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Merge Audio and Video Streams Upon Conversion End (0 = No, 1 = YES)");
	outf(fp, "MovieVideoAudio=%u\n", MovieVideoAudio);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Keyboard Hotkeys --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " (you shouldn\'t edit these directly unless you know what you\'re doing)");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Super Scope Keys:");
	outf(fp, ";%s\n", " Extra Device in Port 1/2 Cycle");
	outf(fp, "KeyExtraEnab1=%u\n", KeyExtraEnab1);
	outf(fp, "KeyExtraEnab2=%u\n", KeyExtraEnab2);
	outf(fp, "KeyExtraRotate=%u\n", KeyExtraRotate);
	outf(fp, "\n");
	outf(fp, ";%s\n", " State Keys:");
	outf(fp, ";%s\n", " Save State / Select Slot Menu / Load State");
	outf(fp, "KeySaveState=%u\n", KeySaveState);
	outf(fp, "KeyStateSelct=%u\n", KeyStateSelct);
	outf(fp, "KeyLoadState=%u\n", KeyLoadState);
	outf(fp, ";%s\n", " Increase / Decrease Slot # / Direct Slot # Select");
	outf(fp, "KeyIncStateSlot=%u\n", KeyIncStateSlot);
	outf(fp, "KeyDecStateSlot=%u\n", KeyDecStateSlot);
	outf(fp, "KeyStateSlc0=%u\n", KeyStateSlc0);
	outf(fp, "KeyStateSlc1=%u\n", KeyStateSlc1);
	outf(fp, "KeyStateSlc2=%u\n", KeyStateSlc2);
	outf(fp, "KeyStateSlc3=%u\n", KeyStateSlc3);
	outf(fp, "KeyStateSlc4=%u\n", KeyStateSlc4);
	outf(fp, "KeyStateSlc5=%u\n", KeyStateSlc5);
	outf(fp, "KeyStateSlc6=%u\n", KeyStateSlc6);
	outf(fp, "KeyStateSlc7=%u\n", KeyStateSlc7);
	outf(fp, "KeyStateSlc8=%u\n", KeyStateSlc8);
	outf(fp, "KeyStateSlc9=%u\n", KeyStateSlc9);
	outf(fp, ";%s\n", " Rewind");
	outf(fp, "KeyRewind=%u\n", KeyRewind);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Speed Keys:");
	outf(fp, ";%s\n", " Fast-Forward, Slow-Motion");
	outf(fp, "KeyFastFrwrd=%u\n", KeyFastFrwrd);
	outf(fp, "KeySlowDown=%u\n", KeySlowDown);
	outf(fp, ";%s\n", " Frame Rate Up/Down (Manual Frameskip)");
	outf(fp, "KeyFRateUp=%u\n", KeyFRateUp);
	outf(fp, "KeyFRateDown=%u\n", KeyFRateDown);
	outf(fp, ";%s\n", " Speed Throttle Up/Down/Reset to Normal (Auto Frameskip)");
	outf(fp, "KeyEmuSpeedUp=%u\n", KeyEmuSpeedUp);
	outf(fp, "KeyEmuSpeedDown=%u\n", KeyEmuSpeedDown);
	outf(fp, "KeyResetSpeed=%u\n", KeyResetSpeed);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Pause Emulation, Frame Advance Keys");
	outf(fp, "EMUPauseKey=%u\n", EMUPauseKey);
	outf(fp, "INCRFrameKey=%u\n", INCRFrameKey);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Shortcuts:");
	outf(fp, ";%s\n", " BG 0-3, Sprite Layer Display Toggles");
	outf(fp, "KeyBGDisble0=%u\n", KeyBGDisble0);
	outf(fp, "KeyBGDisble1=%u\n", KeyBGDisble1);
	outf(fp, "KeyBGDisble2=%u\n", KeyBGDisble2);
	outf(fp, "KeyBGDisble3=%u\n", KeyBGDisble3);
	outf(fp, "KeySprDisble=%u\n", KeySprDisble);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Sound Channel 0-7 Output Toggles");
	outf(fp, "KeyDisableSC0=%u\n", KeyDisableSC0);
	outf(fp, "KeyDisableSC1=%u\n", KeyDisableSC1);
	outf(fp, "KeyDisableSC2=%u\n", KeyDisableSC2);
	outf(fp, "KeyDisableSC3=%u\n", KeyDisableSC3);
	outf(fp, "KeyDisableSC4=%u\n", KeyDisableSC4);
	outf(fp, "KeyDisableSC5=%u\n", KeyDisableSC5);
	outf(fp, "KeyDisableSC6=%u\n", KeyDisableSC6);
	outf(fp, "KeyDisableSC7=%u\n", KeyDisableSC7);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Sound Volume Up/Down");
	outf(fp, "KeyVolUp=%u\n", KeyVolUp);
	outf(fp, "KeyVolDown=%u\n", KeyVolDown);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Quit ZSNES / Load Menu / Reset Game / Panic Key");
	outf(fp, "KeyQuickExit=%u\n", KeyQuickExit);
	outf(fp, "KeyQuickLoad=%u\n", KeyQuickLoad);
	outf(fp, "KeyQuickRst=%u\n", KeyQuickRst);
	outf(fp, "KeyResetAll=%u\n", KeyResetAll);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Clock Display Toggle");
	outf(fp, "KeyQuickClock=%u\n", KeyQuickClock);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Netplay In-Game Chat");
	outf(fp, "KeyQuickChat=%u\n", KeyQuickChat);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Screenshot Hotkey");
	outf(fp, "KeyQuickSnapShot=%u\n", KeyQuickSnapShot);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Capture SPC Hotkey");
	outf(fp, "KeyQuickSaveSPC=%u\n", KeyQuickSaveSPC);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Use Player 3/4 Input as Player 1/2\'s Toggle");
	outf(fp, "KeyUsePlayer1234=%u\n", KeyUsePlayer1234);
	outf(fp, "\n");
	outf(fp, ";%s\n", " FPS Display Toggle");
	outf(fp, "KeyDisplayFPS=%u\n", KeyDisplayFPS);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Video Engine: Old/New Graphic Engine | Windowing | Offset Effects Toggles");
	outf(fp, "KeyNewGfxSwt=%u\n", KeyNewGfxSwt);
	outf(fp, "KeyWinDisble=%u\n", KeyWinDisble);
	outf(fp, "KeyOffsetMSw=%u\n", KeyOffsetMSw);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Movie Chapters: Insert / Go to Previous / Go to Next");
	outf(fp, "KeyInsrtChap=%u\n", KeyInsrtChap);
	outf(fp, "KeyPrevChap=%u\n", KeyPrevChap);
	outf(fp, "KeyNextChap=%u\n", KeyNextChap);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Movie state load mode cycle");
	outf(fp, "KeyRTRCycle=%u\n", KeyRTRCycle);
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Misc --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Calculated Checksum & Hash: Don\'t Edit by Hand !");
	outf(fp, "TimeChecker=%u\n", TimeChecker);
	outf(fp, "PrevBuildNum=%u\n", PrevBuildNum);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Display First-Time Use Reminder (0 = YES, 1 = No)");
	outf(fp, "FirstTimeData=%u\n", FirstTimeData);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Prevent ZSNES from Saving the Configuration on Exit (0 = NO, 1 = Yes)");
	outf(fp, "cfgdontsave=%u\n", cfgdontsave);
	outf(fp, "\n");
	outf(fp, ";%s\n", " - EOF -");
}

unsigned char write_cfg_vars(const char *file) {
	FILE *fp = 0;

	init_cfg_vars();

	if ((fp = fopen(file, "w"))) {
		write_cfg_vars_internal(fp, (int (*)(void *, const char *, ...))fprintf);
		fclose(fp);

		return (1);
	}
	return (0);
}

static size_t base94_decode(const char *buffer) {
	size_t size = 0;
	int i;
	for (i = 4; i >= 0; i--) {
		size *= 94;
		size += (size_t)(buffer[i] - ' ');
	}
	return (size);
}

static char *get_token(char *str, char *delim) {
	static char *pos = 0;
	char *token = 0;

	if (str) // Start a new string?
	{
		pos = str;
	}

	if (pos) {
		// Skip delimiters
		while (*pos && strchr(delim, *pos)) {
			pos++;
		}
		if (*pos) {
			token = pos;

			// Skip non-delimiters
			while (*pos && !strchr(delim, *pos)) {
				// Skip quoted characters
				if ((*pos == '\"') || (*pos == '\'')) {
					char *match_pos = 0;
					if ((match_pos = find_next_match(pos + 1, *pos))) {
						pos = match_pos;
					}
				}
				pos++;
			}
			if (*pos) {
				*pos++ = '\0';
			}
		}
	}
	return (token);
}

static char *char_array_unpack(char *str) {
	char packed[LINE_LENGTH];
	char *p = packed, *token;
	size_t len = 0;
	memset(packed, 0, sizeof(packed));
	for (token = get_token(str, "\\"); token; token = get_token(0, "\\")) {
		if (*token == '0') {
			size_t i = base94_decode(decode_string(token + 1));
			len += i;
			if (len > sizeof(packed)) { break; }
			memset(p, 0, i);
			p += i;
		} else {
			char *decoded = decode_string(token);
			size_t decoded_length = strlen(decoded);
			len += decoded_length;
			if (len > sizeof(packed)) {
				memcpy(p, decoded, sizeof(packed) - (len - decoded_length));
				break;
			}
			memcpy(p, decoded, decoded_length);
			p += decoded_length;
		}
	}
	memcpy(line, packed, sizeof(packed));
	return (line);
}

static void read_int_array(char *line, int *var, size_t size) {
	size_t i;
	char *token;
	*var = (int)atoi(strtok(line, ", \t\r\n"));
	for (i = 1; (i < size) && (token = strtok(0, ", \t\r\n")); i++) {
		var[i] = (int)atoi(token);
	}
}

static void read_cfg_vars_internal(void *fp, char *(*fin)(char *, int, void *), int (*fend)(void *)) {
	while (!fend(fp)) {
		char *p, *var, *value;

		fin(line, LINE_LENGTH, fp);
		if ((p = find_str(line, ";"))) { *p = 0; }
		if ((p = strchr(line, '='))) {
			*p = 0;
			var = line;
			value = p + 1;
			while (isspace(*var)) { var++; }
			while (isspace(*value)) { value++; }
			if ((p = find_str(var, " \t\r\n"))) { *p = 0; }
			if ((p = find_str(value, " \t\r\n"))) { *p = 0; }
			if (!*var || !*value) { continue; }
		} else {
			continue;
		}

		if (!strcmp(var, "GUIComboGameSpec")) {
			GUIComboGameSpec = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GameSpecificInput")) {
			GameSpecificInput = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "Show224Lines")) {
			Show224Lines = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "newengen")) {
			newengen = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "bgfixer")) {
			bgfixer = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "AutoPatch")) {
			AutoPatch = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "DisplayInfo")) {
			DisplayInfo = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "RomInfo")) {
			RomInfo = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "FPSAtStart")) {
			FPSAtStart = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "TimerEnable")) {
			TimerEnable = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "TwelveHourClock")) {
			TwelveHourClock = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "ClockBox")) {
			ClockBox = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "SmallMsgText")) {
			SmallMsgText = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIEnableTransp")) {
			GUIEnableTransp = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "ScreenShotFormat")) {
			ScreenShotFormat = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "cvidmode")) {
			cvidmode = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "CustomResX")) {
			CustomResX = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "CustomResY")) {
			CustomResY = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "vsyncon")) {
			vsyncon = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "libAoDriver")) {
			*libAoDriver = 0;
			strncat(libAoDriver, decode_string(value), sizeof(libAoDriver) - 1);
			continue;
		}
		if (!strcmp(var, "SPCDisable")) {
			SPCDisable = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "soundon")) {
			soundon = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "StereoSound")) {
			StereoSound = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "RevStereo")) {
			RevStereo = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "Surround")) {
			Surround = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "SoundQuality")) {
			SoundQuality = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "MusicRelVol")) {
			MusicRelVol = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "SoundInterpType")) {
			SoundInterpType = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "LowPassFilterType")) {
			LowPassFilterType = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "EchoDis")) {
			EchoDis = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "RewindStates")) {
			RewindStates = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "RewindFrames")) {
			RewindFrames = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "nosaveSRAM")) {
			nosaveSRAM = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "SRAMSave5Sec")) {
			SRAMSave5Sec = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "SRAMState")) {
			SRAMState = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "LatestSave")) {
			LatestSave = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "AutoIncSaveSlot")) {
			AutoIncSaveSlot = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "AutoIncSaveSlotBlock")) {
			AutoIncSaveSlotBlock = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "AutoState")) {
			AutoState = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "PauseLoad")) {
			PauseLoad = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "PauseRewind")) {
			PauseRewind = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "per2exec")) {
			per2exec = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "HacksDisable")) {
			HacksDisable = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "frameskip")) {
			frameskip = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "maxskip")) {
			maxskip = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "FastFwdToggle")) {
			FastFwdToggle = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "FFRatio")) {
			FFRatio = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "SDRatio")) {
			SDRatio = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "EmuSpeed")) {
			EmuSpeed = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "SPC7110Cache")) {
			SPC7110Cache = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "ROMPath")) {
			*ROMPath = 0;
			strncat(ROMPath, decode_string(value), sizeof(ROMPath) - 1);
			continue;
		}
		if (!strcmp(var, "SRAMPath")) {
			*SRAMPath = 0;
			strncat(SRAMPath, decode_string(value), sizeof(SRAMPath) - 1);
			continue;
		}
		if (!strcmp(var, "SStatePath")) {
			*SStatePath = 0;
			strncat(SStatePath, decode_string(value), sizeof(SStatePath) - 1);
			continue;
		}
		if (!strcmp(var, "SnapPath")) {
			*SnapPath = 0;
			strncat(SnapPath, decode_string(value), sizeof(SnapPath) - 1);
			continue;
		}
		if (!strcmp(var, "IPSPath")) {
			*IPSPath = 0;
			strncat(IPSPath, decode_string(value), sizeof(IPSPath) - 1);
			continue;
		}
		if (!strcmp(var, "MoviePath")) {
			*MoviePath = 0;
			strncat(MoviePath, decode_string(value), sizeof(MoviePath) - 1);
			continue;
		}
		if (!strcmp(var, "SPCPath")) {
			*SPCPath = 0;
			strncat(SPCPath, decode_string(value), sizeof(SPCPath) - 1);
			continue;
		}
		if (!strcmp(var, "CHTPath")) {
			*CHTPath = 0;
			strncat(CHTPath, decode_string(value), sizeof(CHTPath) - 1);
			continue;
		}
		if (!strcmp(var, "ComboPath")) {
			*ComboPath = 0;
			strncat(ComboPath, decode_string(value), sizeof(ComboPath) - 1);
			continue;
		}
		if (!strcmp(var, "INPPath")) {
			*INPPath = 0;
			strncat(INPPath, decode_string(value), sizeof(INPPath) - 1);
			continue;
		}
		if (!strcmp(var, "BSXPath")) {
			*BSXPath = 0;
			strncat(BSXPath, decode_string(value), sizeof(BSXPath) - 1);
			continue;
		}
		if (!strcmp(var, "STPath")) {
			*STPath = 0;
			strncat(STPath, decode_string(value), sizeof(STPath) - 1);
			continue;
		}
		if (!strcmp(var, "GNextPath")) {
			*GNextPath = 0;
			strncat(GNextPath, decode_string(value), sizeof(GNextPath) - 1);
			continue;
		}
		if (!strcmp(var, "SGPath")) {
			*SGPath = 0;
			strncat(SGPath, decode_string(value), sizeof(SGPath) - 1);
			continue;
		}
		if (!strcmp(var, "RelPathBase")) {
			RelPathBase = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "guioff")) {
			guioff = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "showallext")) {
			showallext = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIloadfntype")) {
			GUIloadfntype = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "prevloadiname")) {
			memcpy(prevloadiname, char_array_unpack(value), 280);
			continue;
		}
		if (!strcmp(var, "prevloaddnamel")) {
			memcpy(prevloaddnamel, char_array_unpack(value), 5120);
			continue;
		}
		if (!strcmp(var, "prevloadfnamel")) {
			memcpy(prevloadfnamel, char_array_unpack(value), 5120);
			continue;
		}
		if (!strcmp(var, "prevlfreeze")) {
			prevlfreeze = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIRClick")) {
			GUIRClick = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "lhguimouse")) {
			lhguimouse = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "mouseshad")) {
			mouseshad = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "esctomenu")) {
			esctomenu = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "JoyPad1Move")) {
			JoyPad1Move = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "newfont")) {
			newfont = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "savewinpos")) {
			savewinpos = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIwinposx")) {
			read_int_array(value, GUIwinposx, 23);
			continue;
		}
		if (!strcmp(var, "GUIwinposy")) {
			read_int_array(value, GUIwinposy, 23);
			continue;
		}
		if (!strcmp(var, "GUIEffect")) {
			GUIEffect = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIRAdd")) {
			GUIRAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIGAdd")) {
			GUIGAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIBAdd")) {
			GUIBAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUITRAdd")) {
			GUITRAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUITGAdd")) {
			GUITGAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUITBAdd")) {
			GUITBAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIWRAdd")) {
			GUIWRAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIWGAdd")) {
			GUIWGAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "GUIWBAdd")) {
			GUIWBAdd = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "AutoLoadCht")) {
			AutoLoadCht = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "CheatSrcByteSize")) {
			CheatSrcByteSize = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "CheatSrcByteBase")) {
			CheatSrcByteBase = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "CheatSrcSearchType")) {
			CheatSrcSearchType = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "CheatUpperByteOnly")) {
			CheatUpperByteOnly = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "MovieDisplayFrame")) {
			MovieDisplayFrame = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "MovieStartMethod")) {
			MovieStartMethod = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "MZTForceRTR")) {
			MZTForceRTR = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "MovieVideoMode")) {
			MovieVideoMode = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "MovieAudio")) {
			MovieAudio = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "MovieAudioCompress")) {
			MovieAudioCompress = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "MovieVideoAudio")) {
			MovieVideoAudio = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyExtraEnab1")) {
			KeyExtraEnab1 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyExtraEnab2")) {
			KeyExtraEnab2 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyExtraRotate")) {
			KeyExtraRotate = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeySaveState")) {
			KeySaveState = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSelct")) {
			KeyStateSelct = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyLoadState")) {
			KeyLoadState = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyIncStateSlot")) {
			KeyIncStateSlot = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDecStateSlot")) {
			KeyDecStateSlot = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc0")) {
			KeyStateSlc0 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc1")) {
			KeyStateSlc1 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc2")) {
			KeyStateSlc2 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc3")) {
			KeyStateSlc3 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc4")) {
			KeyStateSlc4 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc5")) {
			KeyStateSlc5 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc6")) {
			KeyStateSlc6 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc7")) {
			KeyStateSlc7 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc8")) {
			KeyStateSlc8 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyStateSlc9")) {
			KeyStateSlc9 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyRewind")) {
			KeyRewind = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyFastFrwrd")) {
			KeyFastFrwrd = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeySlowDown")) {
			KeySlowDown = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyFRateUp")) {
			KeyFRateUp = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyFRateDown")) {
			KeyFRateDown = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyEmuSpeedUp")) {
			KeyEmuSpeedUp = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyEmuSpeedDown")) {
			KeyEmuSpeedDown = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyResetSpeed")) {
			KeyResetSpeed = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "EMUPauseKey")) {
			EMUPauseKey = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "INCRFrameKey")) {
			INCRFrameKey = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyBGDisble0")) {
			KeyBGDisble0 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyBGDisble1")) {
			KeyBGDisble1 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyBGDisble2")) {
			KeyBGDisble2 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyBGDisble3")) {
			KeyBGDisble3 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeySprDisble")) {
			KeySprDisble = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisableSC0")) {
			KeyDisableSC0 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisableSC1")) {
			KeyDisableSC1 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisableSC2")) {
			KeyDisableSC2 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisableSC3")) {
			KeyDisableSC3 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisableSC4")) {
			KeyDisableSC4 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisableSC5")) {
			KeyDisableSC5 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisableSC6")) {
			KeyDisableSC6 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisableSC7")) {
			KeyDisableSC7 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyVolUp")) {
			KeyVolUp = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyVolDown")) {
			KeyVolDown = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyQuickExit")) {
			KeyQuickExit = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyQuickLoad")) {
			KeyQuickLoad = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyQuickRst")) {
			KeyQuickRst = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyResetAll")) {
			KeyResetAll = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyQuickClock")) {
			KeyQuickClock = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyQuickChat")) {
			KeyQuickChat = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyQuickSnapShot")) {
			KeyQuickSnapShot = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyQuickSaveSPC")) {
			KeyQuickSaveSPC = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyUsePlayer1234")) {
			KeyUsePlayer1234 = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyDisplayFPS")) {
			KeyDisplayFPS = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyNewGfxSwt")) {
			KeyNewGfxSwt = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyWinDisble")) {
			KeyWinDisble = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyOffsetMSw")) {
			KeyOffsetMSw = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyInsrtChap")) {
			KeyInsrtChap = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyPrevChap")) {
			KeyPrevChap = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyNextChap")) {
			KeyNextChap = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "KeyRTRCycle")) {
			KeyRTRCycle = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "TimeChecker")) {
			TimeChecker = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "PrevBuildNum")) {
			PrevBuildNum = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "FirstTimeData")) {
			FirstTimeData = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "cfgdontsave")) {
			cfgdontsave = (unsigned char)atoui(value);
			continue;
		}
	}
}

unsigned char read_cfg_vars(const char *file) {
	FILE *fp = 0;

	init_cfg_vars();

	if ((fp = fopen(file, "r"))) {
		read_cfg_vars_internal(fp, (char *(*)(char *, int, void *))fgets, (int (*)(void *))feof);
		fclose(fp);
		write_cfg_vars(file);
		return (1);
	}

	write_cfg_vars(file);
	return (0);
}
