/* endmem.asm: emulator scratch tables and buffers. The assembly relied on
   exact symbol order and adjacency, so the layout is reproduced verbatim in an
   inline-asm block. resb N is N bytes, resd N is N*4, resw N is N*2. */
#include "asmdata.h"

/* .bss reservations */
#define EB(sym, n) ASM_GSYM(sym) ".skip " #n "\n" /* resb: n bytes  */
#define ED(sym, n) ASM_GSYM(sym) ".skip (" #n ")*4\n" /* resd: n dwords */
/* resd too in the assembly, but these hold host pointers - a table of them has
   to follow the pointer width, not the dword the original assumed. On i386 the
   two are the same and the block is byte-identical. */
#define EP(sym, n) \
    ASM_GSYM(sym)  \
    ".skip (" #n ")*" ASM_STR(__SIZEOF_POINTER__) "\n"
#define EW(sym, n) ASM_GSYM(sym) ".skip (" #n ")*2\n" /* resw: n words  */
#define EALIAS(sym) ASM_GSYM(sym) /* zero-size alias */

/* .data fills */
#define FILLB(sym, count, val) ASM_GSYM(sym) ".fill " #count ",1," #val "\n"

__asm__(
    ASM_SEC_BSS(".bss")
        EB(wramdataa, 65536)
            EB(ram7fa, 65536)
                ED(Inbetweendat, 4)
                    EP(opcjmptab, 256)

                        EP(Bank0datr8, 256)
                            EP(Bank0datr16, 256)
                                EP(Bank0datw8, 256)
                                    EP(Bank0datw16, 256)

                                        EP(tableA, 256)
                                            EP(tableB, 256)
                                                EP(tableC, 256)
                                                    EP(tableD, 256)
                                                        EP(tableE, 256)
                                                            EP(tableF, 256)
                                                                EP(tableG, 256)
                                                                    EP(tableH, 256)

                                                                        EP(tableAc, 256)
                                                                            EP(tableBc, 256)
                                                                                EP(tableCc, 256)
                                                                                    EP(tableDc, 256)
                                                                                        EP(tableEc, 256)
                                                                                            EP(tableFc, 256)
                                                                                                EP(tableGc, 256)
                                                                                                    EP(tableHc, 256)

                                                                                                        EP(SA1tableA, 256)
                                                                                                            EP(SA1tableB, 256)
                                                                                                                EP(SA1tableC, 256)
                                                                                                                    EP(SA1tableD, 256)
                                                                                                                        EP(SA1tableE, 256)
                                                                                                                            EP(SA1tableF, 256)
                                                                                                                                EP(SA1tableG, 256)
                                                                                                                                    EP(SA1tableH, 256)

                                                                                                                                        EP(tablead, 256)
                                                                                                                                            EP(tableadc, 256)
                                                                                                                                                EP(SA1tablead, 256)

                                                                                                                                                    EP(memtabler8, 256)
                                                                                                                                                        EP(memtablew8, 256)
                                                                                                                                                            EP(memtabler16, 256)
                                                                                                                                                                EP(memtablew16, 256)
                                                                                                                                                                    EB(vidmemch2, 4096)
                                                                                                                                                                        EB(vidmemch4, 4096)
                                                                                                                                                                            EB(vidmemch8, 4096)
                                                                                                                                                                                EP(snesmmap, 256)
                                                                                                                                                                                    EP(snesmap2, 256)
                                                                                                                                                                                        EALIAS(cachebg)
                                                                                                                                                                                            EB(cachebg1, 64)
                                                                                                                                                                                                EB(cachebg2, 64)
                                                                                                                                                                                                    EB(cachebg3, 64)
                                                                                                                                                                                                        EB(cachebg4, 64)
                                                                                                                                                                                                            EB(sprlefttot, 256)
                                                                                                                                                                                                                EB(sprleftpr, 256)
                                                                                                                                                                                                                    EB(sprleftpr1, 256)
                                                                                                                                                                                                                        EB(sprleftpr2, 256)
                                                                                                                                                                                                                            EB(sprleftpr3, 256)
                                                                                                                                                                                                                                EB(sprcnt, 256)
                                                                                                                                                                                                                                    EB(sprstart, 256)
                                                                                                                                                                                                                                        EB(sprtilecnt, 256)
                                                                                                                                                                                                                                            EB(sprend, 256)
                                                                                                                                                                                                                                                EW(sprendx, 256)
                                                                                                                                                                                                                                                    EB(sprpriodata, 288)
                                                                                                                                                                                                                                                        EB(sprprtabc, 64)
                                                                                                                                                                                                                                                            EB(sprprtabu, 64)
                                                                                                                                                                                                                                                                EW(prevpal, 256)
                                                                                                                                                                                                                                                                    EB(winbgdata, 288)
                                                                                                                                                                                                                                                                        EB(winspdata, 288)
                                                                                                                                                                                                                                                                            EP(FxTable, 256)
                                                                                                                                                                                                                                                                                EP(FxTableA1, 256)
                                                                                                                                                                                                                                                                                    EP(FxTableA2, 256)
                                                                                                                                                                                                                                                                                        EP(FxTableA3, 256)
                                                                                                                                                                                                                                                                                            EP(FxTableb, 256)
                                                                                                                                                                                                                                                                                                EP(FxTablebA1, 256)
                                                                                                                                                                                                                                                                                                    EP(FxTablebA2, 256)
                                                                                                                                                                                                                                                                                                        EP(FxTablebA3, 256)
                                                                                                                                                                                                                                                                                                            EP(FxTablec, 256)
                                                                                                                                                                                                                                                                                                                EP(FxTablecA1, 256)
                                                                                                                                                                                                                                                                                                                    EP(FxTablecA2, 256)
                                                                                                                                                                                                                                                                                                                        EP(FxTablecA3, 256)
                                                                                                                                                                                                                                                                                                                            EP(FxTabled, 256)
                                                                                                                                                                                                                                                                                                                                EP(FxTabledA1, 256)
                                                                                                                                                                                                                                                                                                                                    EP(FxTabledA2, 256)
                                                                                                                                                                                                                                                                                                                                        EP(FxTabledA3, 256)
                                                                                                                                                                                                                                                                                                                                            EP(SfxMemTable, 256)
                                                                                                                                                                                                                                                                                                                                                ED(fxxand, 256)
                                                                                                                                                                                                                                                                                                                                                    ED(fxbit01, 256)
                                                                                                                                                                                                                                                                                                                                                        ED(fxbit23, 256)
                                                                                                                                                                                                                                                                                                                                                            ED(fxbit45, 256)
                                                                                                                                                                                                                                                                                                                                                                ED(fxbit67, 256)
                                                                                                                                                                                                                                                                                                                                                                    EP(PLOTJmpa, 64)
                                                                                                                                                                                                                                                                                                                                                                        EP(PLOTJmpb, 64)

                                                                                                                                                                                                                                                                                                                                                                            ED(pal16b, 256)
                                                                                                                                                                                                                                                                                                                                                                                ED(pal16bcl, 256)
                                                                                                                                                                                                                                                                                                                                                                                    ED(pal16bclha, 256)
                                                                                                                                                                                                                                                                                                                                                                                        ED(pal16bxcl, 256)
                                                                                                                                                                                                                                                                                                                                                                                            EB(xtravbuf, 576)
                                                                                                                                                                                                                                                                                                                                                                                                EW(BG1SXl, 256)
                                                                                                                                                                                                                                                                                                                                                                                                    EW(BG2SXl, 256)
                                                                                                                                                                                                                                                                                                                                                                                                        EW(BG3SXl, 256)
                                                                                                                                                                                                                                                                                                                                                                                                            EW(BG4SXl, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                EW(BG1SYl, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                    EW(BG2SYl, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                        EW(BG3SYl, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                            EW(BG4SYl, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                EB(BGMA, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(BGFB, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(BG3PRI, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                            EW(BGOPT1, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                EW(BGOPT2, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    EW(BGOPT3, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        EW(BGOPT4, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            EW(BGPT1, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                EW(BGPT2, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EW(BGPT3, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EW(BGPT4, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EW(BGPT1X, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EW(BGPT2X, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EW(BGPT3X, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EW(BGPT4X, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EW(BGPT1Y, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EW(BGPT2Y, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EW(BGPT3Y, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EW(BGPT4Y, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EW(BGMS1, 1024)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(prdata, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(prdatb, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(prdatc, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ED(ngpalcon2b, 0x20)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ED(ngpalcon4b, 0x20)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ED(ngpalcon8b, 0x20)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(tltype2b, 4096)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(tltype4b, 2048)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(tltype8b, 1024)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ED(ngptrdat, 1024)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ED(ngceax, 1024)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EP(ngcedi, 1024)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EW(bgtxad, 1024)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EP(sprtbng, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(sprtlng, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(mosszng, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(mosenng, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ASM_SEC_END

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ASM_SEC_DATA(".data") ".balign 32\n" FILLB(vidmemch2s, 4096, 0xFF)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FILLB(vidmemch4s, 2048, 0xFF)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FILLB(vidmemch8s, 1024, 0xFF)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ASM_SEC_END

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ASM_SEC_BSS(".bss")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ED(mode7ab, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ED(mode7cd, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ED(mode7xy, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(mode7st, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(t16x161, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(t16x162, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(t16x163, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(t16x164, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(intrlng, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(mode7hr, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(scadsng, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(scadtng, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EW(scbcong, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EP(cpalval, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(cgfxmod, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ED(winboundary, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(winbg1enval, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(winbg2enval, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(winbg3enval, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(winbg4enval, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(winbgobjenval, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(winbgbackenval, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EW(winlogicaval, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(winbg1envals, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(winbg2envals, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(winbg3envals, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(winbg4envals, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(winbgobjenvals, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(winbgbackenvals, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(winbg1envalm, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(winbg2envalm, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(winbg3envalm, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(winbg4envalm, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(winbgobjenvalm, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(winbgbackenvalm, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(FillSubScr, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ED(objclineptr, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ASM_SEC_END

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ASM_SEC_DATA(".data") ".balign 32\n" ASM_GSYM(objwlrpos) ".rept 256\n.long 0xFFFFFFFF\n.endr\n" ASM_GSYM(objwen) ".rept 256\n.short 0xFFFF\n.endr\n" ASM_SEC_END

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ASM_SEC_BSS(".bss")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(SpecialLine, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(bgallchange, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(bg1change, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(bg2change, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EB(bg3change, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EB(bg4change, 256)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EB(bgwinchange, 256)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EB(PrevPicture, 64 * 56 * 2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ASM_SEC_END);
