# Source and Header Files

# C source files
set(ZSNES_C_SRC
    c_init.c
    c_vcache.c
    chips/7110emu.c
    chips/msu1emu.c
    chips/c4emu.c
    chips/c_dsp2proc.c
    chips/c_sa1regs.c
    chips/c_sfxproc.c
    chips/dsp1emu.c
    chips/dsp3emu.c
    chips/dsp4emu.c
    chips/obc1emu.c
    chips/sa1emu.c
    chips/sdd1emu.c
    chips/seta10.c
    chips/seta11.c
    cpu/c_65816d.c
    cpu/c_dma.c
    cpu/c_dsp.c
    cpu/c_dspproc.c
    cpu/c_execute.c
    cpu/c_irq.c
    cpu/c_memory.c
    cpu/c_regs.c
    cpu/c_regsw.c
    cpu/c_table.c
    cpu/c_tablec.c
    cpu/executec.c
    cpu/memtable.c
    effects/burn.c
    effects/smoke.c
    effects/water.c
    gui/c_gui.c
    gui/c_guiwindp.c
    gui/guicheat.c
    gui/guicombo.c
    gui/guifuncs.c
    gui/guikeys.c
    gui/guimisc.c
    gui/guimouse.c
    gui/guitools.c
    gui/menu.c
    initc.c
    mmlib/mm.c
    patch.c
    ui.c
    ver.c
    video/ntsc.c
    video/procvid.c
    video/procvidc.c
    video/sw_draw.c
    zdir.c
    zip/unzip.c
    zip/zpng.c
    zloader.c
    zmovie.c
    zpath.c
    zstate.c
    ztimec.c
    linux/audio.c
    linux/battery.c
    linux/c_sdlintrf.c
    linux/lib.c
    linux/safelib.c
    linux/sdllink.c
    linux/sockserv.c
    linux/sw_draw.c
    linux/gl_draw.c
    mmlib/linux.c
)

# Assembly source files
set(ZSNES_ASM_SRC
    chips/7110proc.asm
    chips/c4proc.asm
    chips/dsp1proc.asm
    chips/dsp2proc.asm
    chips/dsp3proc.asm
    chips/dsp4proc.asm
    chips/fxemu2.asm
    chips/fxemu2b.asm
    chips/fxemu2c.asm
    chips/fxtable.asm
    chips/obc1proc.asm
    chips/sa1proc.asm
    chips/sa1regs.asm
    chips/sfxproc.asm
    chips/st10proc.asm
    chips/st11proc.asm
    cpu/dma.asm
    cpu/dsp.asm
    cpu/dspproc.asm
    cpu/execute.asm
    cpu/irq.asm
    cpu/memory.asm
    cpu/spc700.asm
    cpu/stable.asm
    cpu/table.asm
    cpu/tablec.asm
    endmem.asm
    gui/gui.asm
    init.asm
    vcache.asm
    video/2xsaiw.asm
    video/copyvid.asm
    video/hq2x16.asm
    video/hq2x32.asm
    video/hq3x16.asm
    video/hq3x32.asm
    video/hq4x16.asm
    video/hq4x32.asm
    video/m716text.asm
    video/makev16b.asm
    video/makev16t.asm
    video/makevid.asm
    video/mode716.asm
    video/mode716b.asm
    video/mode716d.asm
    video/mode716e.asm
    video/mode716t.asm
    video/mv16tms.asm
    video/newg162.asm
    video/newgfx.asm
    video/newgfx16.asm
    linux/sdlintrf.asm
)

# Header files
set(ZSNES_HDR
    asm_call.h
    c_init.h
    types.h
    c_intrf.h
    cfg.h
    cpu/c_execute.h
    cpu/../types.h
    cpu/c_regs.h
    cpu/c_regsw.h
    cpu/c_table.h
    cpu/c_tablec.h
    cpu/execute.h
    cpu/regs.h
    cpu/../macros.h
    cpu/stable.h
    debugger.h
    gui/c_gui.h
    gui/../types.h
    gui/c_guiwindp.h
    gui/gui.h
    gui/../macros.h
    gui/guikeys.h
    gui/guiwindp.h
    init.h
    initc.h
    input.h
    link.h
    macros.h
    ui.h
    video/c_mode716.h
    video/procvid.h
    video/../types.h
    zmovie.h
    gblvars.h
    zpath.h
    zip/zunzip.h
    jma/zsnesjma.h
    zstate.h
)
