;Copyright (C) 1997-2008 ZSNES Team ( zsKnight, _Demo_, pagefault, Nach )
;
;http://www.zsnes.com
;http://sourceforge.net/projects/zsnes
;https://zsnes.bountysource.com
;
;This program is free software; you can redistribute it and/or
;modify it under the terms of the GNU General Public License
;version 2 as published by the Free Software Foundation.
;
;This program is distributed in the hope that it will be useful,
;but WITHOUT ANY WARRANTY; without even the implied warranty of
;MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;GNU General Public License for more details.
;
;You should have received a copy of the GNU General Public License
;along with this program; if not, write to the Free Software
;Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



; makev16t macros


;*******************************************************
; Processes & Draws 4-bit sprites for both main & sub
;*******************************************************










;*******************************************************
; Processes & Draws 4-bit sprites w/ transparency
;*******************************************************






























;*******************************************************
; Processes & Draws 8x8 tiles for both main & sub screen
;*******************************************************









;*******************************************************
; Processes & Draws 8x8 tiles in 2, 4, & 8 bit mode
;*******************************************************















; end makev16t
; ****************************************************
; ****************************************************

;*******************************************************
; DrawLine 16bit                  Draws the current line
;*******************************************************
; use curypos+bg1scroly for y location and bg1scrolx for x location
; use bg1ptr(b,c,d) for the pointer to the tile number contents
; use bg1objptr for the pointer to the object tile contents



















;*******************************************************
; Processes & Draws 8x8 offset mode in Mode 2/4
;*******************************************************
