/*
Config file handler generated by Nach's Config file handler creator.
*/

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "input.h"

#define LINE_LENGTH 262144
static char line[LINE_LENGTH];

static char *find_next_match(char *str, char match_char) {
	char *pos = 0;

	while (*str) {
		if (*str == match_char) {
			pos = str;
			break;
		}
		if (*str == '\\') {
			if (str[1]) {
				str++;
			} else {
				break;
			}
		}
		str++;
	}
	return (pos);
}

static char *find_str(char *str, char *match_str) {
	char *pos = 0;

	while (*str) {
		if (strchr(match_str, *str)) {
			pos = str;
			break;
		}
		if ((*str == '\"') || (*str == '\'')) {
			char *match_pos = 0;
			if ((match_pos = find_next_match(str + 1, *str))) {
				str = match_pos;
			}
		}
		str++;
	}
	return (pos);
}

static int atoui(const char *nptr) {
	return (strtoul(nptr, 0, 10));
}

// Copyright (C) 1997-2008 ZSNES Team ( zsKnight, _Demo_, pagefault, Nach )
//
// http://www.zsnes.com
// http://sourceforge.net/projects/zsnes
// https://zsnes.bountysource.com
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// version 2 as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

unsigned char pl1contrl = 1;
unsigned int pl1selk = 54;
unsigned int pl1startk = 28;
unsigned int pl1upk = 90;
unsigned int pl1downk = 96;
unsigned int pl1leftk = 92;
unsigned int pl1rightk = 94;
unsigned int pl1Xk = 31;
unsigned int pl1Ak = 45;
unsigned int pl1Lk = 32;
unsigned int pl1Yk = 30;
unsigned int pl1Bk = 44;
unsigned int pl1Rk = 46;
unsigned int pl1Atk = 0;
unsigned int pl1Btk = 0;
unsigned int pl1Xtk = 0;
unsigned int pl1Ytk = 0;
unsigned int pl1Ltk = 0;
unsigned int pl1Rtk = 0;
unsigned int pl1ULk = 0;
unsigned int pl1URk = 0;
unsigned int pl1DLk = 0;
unsigned int pl1DRk = 0;

unsigned char pl2contrl = 0;
unsigned int pl2selk = 0;
unsigned int pl2startk = 0;
unsigned int pl2upk = 0;
unsigned int pl2downk = 0;
unsigned int pl2leftk = 0;
unsigned int pl2rightk = 0;
unsigned int pl2Xk = 0;
unsigned int pl2Ak = 0;
unsigned int pl2Lk = 0;
unsigned int pl2Yk = 0;
unsigned int pl2Bk = 0;
unsigned int pl2Rk = 0;
unsigned int pl2Atk = 0;
unsigned int pl2Btk = 0;
unsigned int pl2Xtk = 0;
unsigned int pl2Ytk = 0;
unsigned int pl2Ltk = 0;
unsigned int pl2Rtk = 0;
unsigned int pl2ULk = 0;
unsigned int pl2URk = 0;
unsigned int pl2DLk = 0;
unsigned int pl2DRk = 0;

unsigned char pl3contrl = 0;
unsigned int pl3selk = 0;
unsigned int pl3startk = 0;
unsigned int pl3upk = 0;
unsigned int pl3downk = 0;
unsigned int pl3leftk = 0;
unsigned int pl3rightk = 0;
unsigned int pl3Xk = 0;
unsigned int pl3Ak = 0;
unsigned int pl3Lk = 0;
unsigned int pl3Yk = 0;
unsigned int pl3Bk = 0;
unsigned int pl3Rk = 0;
unsigned int pl3Atk = 0;
unsigned int pl3Btk = 0;
unsigned int pl3Xtk = 0;
unsigned int pl3Ytk = 0;
unsigned int pl3Ltk = 0;
unsigned int pl3Rtk = 0;
unsigned int pl3ULk = 0;
unsigned int pl3URk = 0;
unsigned int pl3DLk = 0;
unsigned int pl3DRk = 0;

unsigned char pl4contrl = 0;
unsigned int pl4selk = 0;
unsigned int pl4startk = 0;
unsigned int pl4upk = 0;
unsigned int pl4downk = 0;
unsigned int pl4leftk = 0;
unsigned int pl4rightk = 0;
unsigned int pl4Xk = 0;
unsigned int pl4Ak = 0;
unsigned int pl4Lk = 0;
unsigned int pl4Yk = 0;
unsigned int pl4Bk = 0;
unsigned int pl4Rk = 0;
unsigned int pl4Atk = 0;
unsigned int pl4Btk = 0;
unsigned int pl4Xtk = 0;
unsigned int pl4Ytk = 0;
unsigned int pl4Ltk = 0;
unsigned int pl4Rtk = 0;
unsigned int pl4ULk = 0;
unsigned int pl4URk = 0;
unsigned int pl4DLk = 0;
unsigned int pl4DRk = 0;

unsigned char pl5contrl = 0;
unsigned int pl5selk = 0;
unsigned int pl5startk = 0;
unsigned int pl5upk = 0;
unsigned int pl5downk = 0;
unsigned int pl5leftk = 0;
unsigned int pl5rightk = 0;
unsigned int pl5Xk = 0;
unsigned int pl5Ak = 0;
unsigned int pl5Lk = 0;
unsigned int pl5Yk = 0;
unsigned int pl5Bk = 0;
unsigned int pl5Rk = 0;
unsigned int pl5Atk = 0;
unsigned int pl5Btk = 0;
unsigned int pl5Xtk = 0;
unsigned int pl5Ytk = 0;
unsigned int pl5Ltk = 0;
unsigned int pl5Rtk = 0;
unsigned int pl5ULk = 0;
unsigned int pl5URk = 0;
unsigned int pl5DLk = 0;
unsigned int pl5DRk = 0;

unsigned short joy_sensitivity = 16384;

unsigned char pl12s34 = 0;

unsigned char AllowUDLR = 0;

unsigned char Turbo30hz = 1;

unsigned char mouse1lh = 0;
unsigned char mouse2lh = 0;

unsigned int SSAutoFire = 13;
unsigned int SSPause = 14;

unsigned char device1 = 0;
unsigned char device2 = 0;

static unsigned char psr_init_done = 0;
static void init_input_vars() {
	if (!psr_init_done) {
		psr_init_done = 1;
	}
}

static void write_input_vars_internal(void *fp, int (*outf)(void *, const char *, ...)) {
	outf(fp, ";%s\n", " PSR-produced config file (stock default in CAPS)");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Note, if you\'re worried you messed up a setting, removing the line will have");
	outf(fp, ";%s\n", " ZSNES use the default settings for that option.");
	outf(fp, ";%s\n", " The next time ZSNES is run, the line will reappear with the default settings.");
	outf(fp, "\n");
	outf(fp, ";%s\n", "  ----");
	outf(fp, ";%s\n", " -- Input --");
	outf(fp, ";%s\n", "  ----");
	outf(fp, "\n");
	outf(fp, ";%s\n", " Player 1 Input");
	outf(fp, ";%s\n", " Input Device: 0 = Unplugged, 1 = KEYBOARD/GAMEPAD");
	outf(fp, "pl1contrl=%u\n", pl1contrl);
	outf(fp, ";%s\n", " Keys for Select, Start, Up, Down, Left, Right, X, A, L, Y, B, R");
	outf(fp, "pl1selk=%u\n", pl1selk);
	outf(fp, "pl1startk=%u\n", pl1startk);
	outf(fp, "pl1upk=%u\n", pl1upk);
	outf(fp, "pl1downk=%u\n", pl1downk);
	outf(fp, "pl1leftk=%u\n", pl1leftk);
	outf(fp, "pl1rightk=%u\n", pl1rightk);
	outf(fp, "pl1Xk=%u\n", pl1Xk);
	outf(fp, "pl1Ak=%u\n", pl1Ak);
	outf(fp, "pl1Lk=%u\n", pl1Lk);
	outf(fp, "pl1Yk=%u\n", pl1Yk);
	outf(fp, "pl1Bk=%u\n", pl1Bk);
	outf(fp, "pl1Rk=%u\n", pl1Rk);
	outf(fp, ";%s\n", " Turbo Keys for A, B, X, Y, L, R");
	outf(fp, "pl1Atk=%u\n", pl1Atk);
	outf(fp, "pl1Btk=%u\n", pl1Btk);
	outf(fp, "pl1Xtk=%u\n", pl1Xtk);
	outf(fp, "pl1Ytk=%u\n", pl1Ytk);
	outf(fp, "pl1Ltk=%u\n", pl1Ltk);
	outf(fp, "pl1Rtk=%u\n", pl1Rtk);
	outf(fp, ";%s\n", " Diagonal Keys for Up-Left, Up-Right, Down-Left, Down-Right");
	outf(fp, "pl1ULk=%u\n", pl1ULk);
	outf(fp, "pl1URk=%u\n", pl1URk);
	outf(fp, "pl1DLk=%u\n", pl1DLk);
	outf(fp, "pl1DRk=%u\n", pl1DRk);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Player 2");
	outf(fp, ";%s\n", " Input Device: 0 = UNPLUGGED, 1 = Keyboard/Gamepad");
	outf(fp, "pl2contrl=%u\n", pl2contrl);
	outf(fp, ";%s\n", " Keys for Select, Start, Up, Down, Left, Right, X, A, L, Y, B, R");
	outf(fp, "pl2selk=%u\n", pl2selk);
	outf(fp, "pl2startk=%u\n", pl2startk);
	outf(fp, "pl2upk=%u\n", pl2upk);
	outf(fp, "pl2downk=%u\n", pl2downk);
	outf(fp, "pl2leftk=%u\n", pl2leftk);
	outf(fp, "pl2rightk=%u\n", pl2rightk);
	outf(fp, "pl2Xk=%u\n", pl2Xk);
	outf(fp, "pl2Ak=%u\n", pl2Ak);
	outf(fp, "pl2Lk=%u\n", pl2Lk);
	outf(fp, "pl2Yk=%u\n", pl2Yk);
	outf(fp, "pl2Bk=%u\n", pl2Bk);
	outf(fp, "pl2Rk=%u\n", pl2Rk);
	outf(fp, ";%s\n", " Turbo Keys for A, B, X, Y, L, R");
	outf(fp, "pl2Atk=%u\n", pl2Atk);
	outf(fp, "pl2Btk=%u\n", pl2Btk);
	outf(fp, "pl2Xtk=%u\n", pl2Xtk);
	outf(fp, "pl2Ytk=%u\n", pl2Ytk);
	outf(fp, "pl2Ltk=%u\n", pl2Ltk);
	outf(fp, "pl2Rtk=%u\n", pl2Rtk);
	outf(fp, ";%s\n", " Diagonal Keys for Up-Left, Up-Right, Down-Left, Down-Right");
	outf(fp, "pl2ULk=%u\n", pl2ULk);
	outf(fp, "pl2URk=%u\n", pl2URk);
	outf(fp, "pl2DLk=%u\n", pl2DLk);
	outf(fp, "pl2DRk=%u\n", pl2DRk);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Player 3");
	outf(fp, ";%s\n", " Input Device: 0 = UNPLUGGED, 1 = Keyboard/Gamepad");
	outf(fp, "pl3contrl=%u\n", pl3contrl);
	outf(fp, ";%s\n", " Keys for Select, Start, Up, Down, Left, Right, X, A, L, Y, B, R");
	outf(fp, "pl3selk=%u\n", pl3selk);
	outf(fp, "pl3startk=%u\n", pl3startk);
	outf(fp, "pl3upk=%u\n", pl3upk);
	outf(fp, "pl3downk=%u\n", pl3downk);
	outf(fp, "pl3leftk=%u\n", pl3leftk);
	outf(fp, "pl3rightk=%u\n", pl3rightk);
	outf(fp, "pl3Xk=%u\n", pl3Xk);
	outf(fp, "pl3Ak=%u\n", pl3Ak);
	outf(fp, "pl3Lk=%u\n", pl3Lk);
	outf(fp, "pl3Yk=%u\n", pl3Yk);
	outf(fp, "pl3Bk=%u\n", pl3Bk);
	outf(fp, "pl3Rk=%u\n", pl3Rk);
	outf(fp, ";%s\n", " Turbo Keys for A, B, X, Y, L, R");
	outf(fp, "pl3Atk=%u\n", pl3Atk);
	outf(fp, "pl3Btk=%u\n", pl3Btk);
	outf(fp, "pl3Xtk=%u\n", pl3Xtk);
	outf(fp, "pl3Ytk=%u\n", pl3Ytk);
	outf(fp, "pl3Ltk=%u\n", pl3Ltk);
	outf(fp, "pl3Rtk=%u\n", pl3Rtk);
	outf(fp, ";%s\n", " Diagonal Keys for Up-Left, Up-Right, Down-Left, Down-Right");
	outf(fp, "pl3ULk=%u\n", pl3ULk);
	outf(fp, "pl3URk=%u\n", pl3URk);
	outf(fp, "pl3DLk=%u\n", pl3DLk);
	outf(fp, "pl3DRk=%u\n", pl3DRk);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Player 4");
	outf(fp, ";%s\n", " Input Device: 0 = UNPLUGGED, 1 = Keyboard/Gamepad");
	outf(fp, "pl4contrl=%u\n", pl4contrl);
	outf(fp, ";%s\n", " Keys for Select, Start, Up, Down, Left, Right, X, A, L, Y, B, R");
	outf(fp, "pl4selk=%u\n", pl4selk);
	outf(fp, "pl4startk=%u\n", pl4startk);
	outf(fp, "pl4upk=%u\n", pl4upk);
	outf(fp, "pl4downk=%u\n", pl4downk);
	outf(fp, "pl4leftk=%u\n", pl4leftk);
	outf(fp, "pl4rightk=%u\n", pl4rightk);
	outf(fp, "pl4Xk=%u\n", pl4Xk);
	outf(fp, "pl4Ak=%u\n", pl4Ak);
	outf(fp, "pl4Lk=%u\n", pl4Lk);
	outf(fp, "pl4Yk=%u\n", pl4Yk);
	outf(fp, "pl4Bk=%u\n", pl4Bk);
	outf(fp, "pl4Rk=%u\n", pl4Rk);
	outf(fp, ";%s\n", " Turbo Keys for A, B, X, Y, L, R");
	outf(fp, "pl4Atk=%u\n", pl4Atk);
	outf(fp, "pl4Btk=%u\n", pl4Btk);
	outf(fp, "pl4Xtk=%u\n", pl4Xtk);
	outf(fp, "pl4Ytk=%u\n", pl4Ytk);
	outf(fp, "pl4Ltk=%u\n", pl4Ltk);
	outf(fp, "pl4Rtk=%u\n", pl4Rtk);
	outf(fp, ";%s\n", " Diagonal Keys for Up-Left, Up-Right, Down-Left, Down-Right");
	outf(fp, "pl4ULk=%u\n", pl4ULk);
	outf(fp, "pl4URk=%u\n", pl4URk);
	outf(fp, "pl4DLk=%u\n", pl4DLk);
	outf(fp, "pl4DRk=%u\n", pl4DRk);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Player 5");
	outf(fp, ";%s\n", " Input Device: 0 = UNPLUGGED, 1 = Keyboard/Gamepad");
	outf(fp, "pl5contrl=%u\n", pl5contrl);
	outf(fp, ";%s\n", " Keys for Select, Start, Up, Down, Left, Right, X, A, L, Y, B, R");
	outf(fp, "pl5selk=%u\n", pl5selk);
	outf(fp, "pl5startk=%u\n", pl5startk);
	outf(fp, "pl5upk=%u\n", pl5upk);
	outf(fp, "pl5downk=%u\n", pl5downk);
	outf(fp, "pl5leftk=%u\n", pl5leftk);
	outf(fp, "pl5rightk=%u\n", pl5rightk);
	outf(fp, "pl5Xk=%u\n", pl5Xk);
	outf(fp, "pl5Ak=%u\n", pl5Ak);
	outf(fp, "pl5Lk=%u\n", pl5Lk);
	outf(fp, "pl5Yk=%u\n", pl5Yk);
	outf(fp, "pl5Bk=%u\n", pl5Bk);
	outf(fp, "pl5Rk=%u\n", pl5Rk);
	outf(fp, ";%s\n", " Turbo Keys for A, B, X, Y, L, R");
	outf(fp, "pl5Atk=%u\n", pl5Atk);
	outf(fp, "pl5Btk=%u\n", pl5Btk);
	outf(fp, "pl5Xtk=%u\n", pl5Xtk);
	outf(fp, "pl5Ytk=%u\n", pl5Ytk);
	outf(fp, "pl5Ltk=%u\n", pl5Ltk);
	outf(fp, "pl5Rtk=%u\n", pl5Rtk);
	outf(fp, ";%s\n", " Diagonal Keys for Up-Left, Up-Right, Down-Left, Down-Right");
	outf(fp, "pl5ULk=%u\n", pl5ULk);
	outf(fp, "pl5URk=%u\n", pl5URk);
	outf(fp, "pl5DLk=%u\n", pl5DLk);
	outf(fp, "pl5DRk=%u\n", pl5DRk);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Joystick Sensitivity [0..32767]");
	outf(fp, ";%s\n", " Change this value if you have input issues. Higher value = less sensitive.");
	outf(fp, ";%s\n", " If your joystick is not being read at all, try 128 or other low values.");
	outf(fp, "joy_sensitivity=%u\n", joy_sensitivity);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Share Player 3 & 4 Control Inputs w/Player 1 & 2 (0 = DISABLE, 1 = Enable)");
	outf(fp, ";%s\n", " Allow 2 devices to be  used for one player");
	outf(fp, ";%s\n", " (enabling this disables Multiplayer 5 support).");
	outf(fp, "pl12s34=%u\n", pl12s34);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Allow Up+Down and Left+Right Pad Input (0 = NO, 1 = Yes)");
	outf(fp, "AllowUDLR=%u\n", AllowUDLR);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Turbo Keys Equal 30 Presses/sec Instead of 60 (0 = No, 1 = YES)");
	outf(fp, "Turbo30hz=%u\n", Turbo30hz);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Left Handed Mouse Behavior for SNES Devices (0 = NO SWAP, 1 = Swap)");
	outf(fp, ";%s\n", " (swap left and right mouse buttons)");
	outf(fp, "mouse1lh=%u ;First device\n", mouse1lh);
	outf(fp, "mouse2lh=%u ;Second device\n", mouse2lh);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Super Scope Buttons");
	outf(fp, "SSAutoFire=%u\n", SSAutoFire);
	outf(fp, "SSPause=%u\n", SSPause);
	outf(fp, "\n");
	outf(fp, ";%s\n", " Port 1 and Port 2 device settings (0 = GAMEPAD, 1 = Mouse)");
	outf(fp, "device1=%u\n", device1);
	outf(fp, ";%s\n", " (0 = GAMEPAD, 1 = Mouse, 2 = Super Scope, 3 = 1 Justifier, 4 = 2 Justifiers)");
	outf(fp, "device2=%u\n", device2);
}

unsigned char write_input_vars(const char *file) {
	FILE *fp = 0;

	init_input_vars();

	if ((fp = fopen(file, "w"))) {
		write_input_vars_internal(fp, (int (*)(void *, const char *, ...))fprintf);
		fclose(fp);

		return (1);
	}
	return (0);
}

static void read_input_vars_internal(void *fp, char *(*fin)(char *, int, void *), int (*fend)(void *)) {
	while (!fend(fp)) {
		char *p, *var, *value;

		fin(line, LINE_LENGTH, fp);
		if ((p = find_str(line, ";"))) { *p = 0; }
		if ((p = strchr(line, '='))) {
			*p = 0;
			var = line;
			value = p + 1;
			while (isspace(*var)) { var++; }
			while (isspace(*value)) { value++; }
			if ((p = find_str(var, " \t\r\n"))) { *p = 0; }
			if ((p = find_str(value, " \t\r\n"))) { *p = 0; }
			if (!*var || !*value) { continue; }
		} else {
			continue;
		}

		if (!strcmp(var, "pl1contrl")) {
			pl1contrl = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1selk")) {
			pl1selk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1startk")) {
			pl1startk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1upk")) {
			pl1upk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1downk")) {
			pl1downk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1leftk")) {
			pl1leftk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1rightk")) {
			pl1rightk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Xk")) {
			pl1Xk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Ak")) {
			pl1Ak = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Lk")) {
			pl1Lk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Yk")) {
			pl1Yk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Bk")) {
			pl1Bk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Rk")) {
			pl1Rk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Atk")) {
			pl1Atk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Btk")) {
			pl1Btk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Xtk")) {
			pl1Xtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Ytk")) {
			pl1Ytk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Ltk")) {
			pl1Ltk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1Rtk")) {
			pl1Rtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1ULk")) {
			pl1ULk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1URk")) {
			pl1URk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1DLk")) {
			pl1DLk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl1DRk")) {
			pl1DRk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2contrl")) {
			pl2contrl = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2selk")) {
			pl2selk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2startk")) {
			pl2startk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2upk")) {
			pl2upk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2downk")) {
			pl2downk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2leftk")) {
			pl2leftk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2rightk")) {
			pl2rightk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Xk")) {
			pl2Xk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Ak")) {
			pl2Ak = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Lk")) {
			pl2Lk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Yk")) {
			pl2Yk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Bk")) {
			pl2Bk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Rk")) {
			pl2Rk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Atk")) {
			pl2Atk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Btk")) {
			pl2Btk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Xtk")) {
			pl2Xtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Ytk")) {
			pl2Ytk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Ltk")) {
			pl2Ltk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2Rtk")) {
			pl2Rtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2ULk")) {
			pl2ULk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2URk")) {
			pl2URk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2DLk")) {
			pl2DLk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl2DRk")) {
			pl2DRk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3contrl")) {
			pl3contrl = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3selk")) {
			pl3selk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3startk")) {
			pl3startk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3upk")) {
			pl3upk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3downk")) {
			pl3downk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3leftk")) {
			pl3leftk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3rightk")) {
			pl3rightk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Xk")) {
			pl3Xk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Ak")) {
			pl3Ak = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Lk")) {
			pl3Lk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Yk")) {
			pl3Yk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Bk")) {
			pl3Bk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Rk")) {
			pl3Rk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Atk")) {
			pl3Atk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Btk")) {
			pl3Btk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Xtk")) {
			pl3Xtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Ytk")) {
			pl3Ytk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Ltk")) {
			pl3Ltk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3Rtk")) {
			pl3Rtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3ULk")) {
			pl3ULk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3URk")) {
			pl3URk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3DLk")) {
			pl3DLk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl3DRk")) {
			pl3DRk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4contrl")) {
			pl4contrl = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4selk")) {
			pl4selk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4startk")) {
			pl4startk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4upk")) {
			pl4upk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4downk")) {
			pl4downk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4leftk")) {
			pl4leftk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4rightk")) {
			pl4rightk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Xk")) {
			pl4Xk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Ak")) {
			pl4Ak = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Lk")) {
			pl4Lk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Yk")) {
			pl4Yk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Bk")) {
			pl4Bk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Rk")) {
			pl4Rk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Atk")) {
			pl4Atk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Btk")) {
			pl4Btk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Xtk")) {
			pl4Xtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Ytk")) {
			pl4Ytk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Ltk")) {
			pl4Ltk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4Rtk")) {
			pl4Rtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4ULk")) {
			pl4ULk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4URk")) {
			pl4URk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4DLk")) {
			pl4DLk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl4DRk")) {
			pl4DRk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5contrl")) {
			pl5contrl = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5selk")) {
			pl5selk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5startk")) {
			pl5startk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5upk")) {
			pl5upk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5downk")) {
			pl5downk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5leftk")) {
			pl5leftk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5rightk")) {
			pl5rightk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Xk")) {
			pl5Xk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Ak")) {
			pl5Ak = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Lk")) {
			pl5Lk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Yk")) {
			pl5Yk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Bk")) {
			pl5Bk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Rk")) {
			pl5Rk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Atk")) {
			pl5Atk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Btk")) {
			pl5Btk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Xtk")) {
			pl5Xtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Ytk")) {
			pl5Ytk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Ltk")) {
			pl5Ltk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5Rtk")) {
			pl5Rtk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5ULk")) {
			pl5ULk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5URk")) {
			pl5URk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5DLk")) {
			pl5DLk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl5DRk")) {
			pl5DRk = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "joy_sensitivity")) {
			joy_sensitivity = (unsigned short)atoui(value);
			continue;
		}
		if (!strcmp(var, "pl12s34")) {
			pl12s34 = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "AllowUDLR")) {
			AllowUDLR = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "Turbo30hz")) {
			Turbo30hz = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "mouse1lh")) {
			mouse1lh = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "mouse2lh")) {
			mouse2lh = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "SSAutoFire")) {
			SSAutoFire = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "SSPause")) {
			SSPause = (unsigned int)atoui(value);
			continue;
		}
		if (!strcmp(var, "device1")) {
			device1 = (unsigned char)atoui(value);
			continue;
		}
		if (!strcmp(var, "device2")) {
			device2 = (unsigned char)atoui(value);
			continue;
		}
	}
}

unsigned char read_input_vars(const char *file) {
	FILE *fp = 0;

	init_input_vars();

	if ((fp = fopen(file, "r"))) {
		read_input_vars_internal(fp, (char *(*)(char *, int, void *))fgets, (int (*)(void *))feof);
		fclose(fp);
		write_input_vars(file);
		return (1);
	}

	write_input_vars(file);
	return (0);
}
