/*
Config file handler header generated by Nach's Config file handler creator.
*/

#ifdef __cplusplus
extern "C" {
#endif

unsigned char read_md_vars(const char *);
unsigned char write_md_vars(const char *);

extern char md_raw_file[50];
extern char md_pcm_audio[50];
extern char md_compressed_audio[50];
extern char md_logo[50];
extern char md_ntsc[20];
extern char md_pal[5];
extern char md_file[50];
extern char md_prog[50];
extern char md_raw[150];
extern char md_other[75];
extern char md_no_sound[25];
extern char md_sound[100];
extern char md_compressed_sound[100];
extern char md_x264[100];
extern char md_ffv1[100];
extern char md_xvid[100];
extern char md_command[256];
extern char md_audio_compress[256];
extern char md_merge[256];
extern char md_custom_temp1[150];
extern char md_custom_temp2[150];
extern char md_custom_temp3[150];
extern unsigned char md_custom_passes;
extern char md_custom_first_pass[512];
extern char md_custom_middle_passes[512];
extern char md_custom_last_pass[512];
extern char md_custom_pass_log_file[50];
extern char md_custom_pass_log_file2[50];

#ifdef __cplusplus
}
#endif
