######################################################################
# Automatically generated by qmake (2.01a) Sun May 27 02:50:31 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += load.h ui.h
FORMS += debugger.ui
SOURCES += load.cpp ui.cpp
